---
# tasks file for websetup

- name: install httpd
  package:
        name: "httpd"
        state: present
- name: copy contents
  copy:
        content: "Now at webserver {{ ansible_default_ipv4.address }}"
        dest: /var/www/html/index.html
- name: service httpd start
  service:
        name: "httpd"
        state: started
