---
# tasks file for ec2_lb
- name: Launch ec2 instance load balancer
  ec2:
          aws_access_key: "{{ access_key }}"
          aws_secret_key: "{{ secret_key }}"
          image: ami-0ebc1ac48dfd14136
          instance_type: t2.micro          
          count: 1
          vpc_subnet_id: subnet-bdc3f3d5
          assign_public_ip: yes
          region: ap-south-1
          instance_tags:
                  name: lbserver
          group_id: "sg-0baed0ae20bfc83eb"
          key_name: keyt
          wait: yes
